# Comparing classifiers for multi-class classifications of handwritten digits

### KNN, logistic regression, SVM, kernel SVM, and neural networks

### complete dataset is available here: http://yann.lecun.com/exdb/mnist/.

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt

from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import svm

import numpy as np
import pandas as pd 

from sklearn.model_selection import train_test_split
import scipy.io as spio
import scipy.io as sio
from sklearn.neural_network import MLPClassifier

data_path = "./data"


In [2]:
np.random.seed(0)

In [3]:
import os
cwd=os.getcwd()
cwd

'C:\\Users\\stuti\\Desktop\\ISYE 6740_Summer2023\\HW 4\\homework4\\data'

In [18]:
data = sio.loadmat("mnist_10digits.mat")

In [20]:
#standardizing features 

X_train = data["xtrain"]/255
y_train= data["ytrain"].ravel()
X_test = data["xtest"]/255
y_test = data["ytest"].ravel()
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [22]:
#fit KNN using reduced datasets 

model = KNeighborsClassifier(3)
model.fit(X_train_sm, y_train_sm)
print(model)

#testing dataset

# make predictions
expected = y_test
predicted = model.predict(X_test)

# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))




KNeighborsClassifier(n_neighbors=3)
              precision    recall  f1-score   support

           0       0.95      0.98      0.96      5923
           1       0.90      0.99      0.94      6742
           2       0.96      0.90      0.93      5958
           3       0.91      0.93      0.92      6131
           4       0.95      0.91      0.93      5842
           5       0.92      0.91      0.92      5421
           6       0.96      0.97      0.97      5918
           7       0.93      0.94      0.93      6265
           8       0.97      0.85      0.90      5851
           9       0.88      0.92      0.90      5949

    accuracy                           0.93     60000
   macro avg       0.93      0.93      0.93     60000
weighted avg       0.93      0.93      0.93     60000

[[5830    3   14    4    2   26   33    4    4    3]
 [   0 6696   12    8    8    0    4    8    3    3]
 [  97  183 5390   39    7   11   24  148   42   17]
 [  22   57   67 5694    2  119    6   48   61

In [25]:
#logistic regression

model_LR = LogisticRegression(solver='lbfgs', max_iter=1000)
model_LR.fit(X_train, y_train)
print(model_LR)


#testing data
# make predictions
expected_LR_test = y_test
predicted_LR_test = model_LR.predict(X_test)

# summarize the fit of the model
print(metrics.classification_report(expected_LR_test, predicted_LR_test))
print(metrics.confusion_matrix(expected_LR_test, predicted_LR_test))



LogisticRegression(max_iter=1000)
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       980
           1       0.96      0.98      0.97      1135
           2       0.93      0.90      0.91      1032
           3       0.90      0.92      0.91      1010
           4       0.94      0.94      0.94       982
           5       0.90      0.87      0.88       892
           6       0.94      0.95      0.95       958
           7       0.93      0.92      0.93      1028
           8       0.88      0.88      0.88       974
           9       0.91      0.92      0.91      1009

    accuracy                           0.93     10000
   macro avg       0.92      0.92      0.92     10000
weighted avg       0.93      0.93      0.93     10000

[[ 955    0    2    4    1   10    4    3    1    0]
 [   0 1110    5    2    0    2    3    2   11    0]
 [   6    9  930   14   10    3   12   10   34    4]
 [   4    1   16  925    1   23    2   10   19  

In [26]:
# fit a SVM model to the data
model_svm = SVC(kernel='rbf')
model_svm.fit(X_train_sm, y_train_sm)
print(model_svm)


#testing data

# make predictions
expected_svm_test = y_test
predicted_svm_test = model_svm.predict(X_test)


# summarize the fit of the model
print(metrics.classification_report(expected_svm_test, predicted_svm_test))
print(metrics.confusion_matrix(expected_svm_test, predicted_svm_test))



SVC()
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       980
           1       0.98      0.99      0.98      1135
           2       0.94      0.95      0.94      1032
           3       0.93      0.95      0.94      1010
           4       0.95      0.95      0.95       982
           5       0.95      0.93      0.94       892
           6       0.96      0.97      0.96       958
           7       0.96      0.93      0.95      1028
           8       0.96      0.94      0.95       974
           9       0.94      0.94      0.94      1009

    accuracy                           0.95     10000
   macro avg       0.95      0.95      0.95     10000
weighted avg       0.95      0.95      0.95     10000

[[ 965    0    2    0    0    6    5    1    1    0]
 [   0 1123    2    2    1    2    2    0    2    1]
 [   7    1  979   10    3    0    8   10   13    1]
 [   0    0   17  960    1   11    1    8    6    6]
 [   2    1    6    0  

In [27]:
#kernel SVM

clf_svm = svm.SVC(kernel='linear', C = 0.01)
clf_svm.fit(X_train_sm, y_train_sm)


#testing data

# make predictions
expected_clf_svm_test = y_test
predicted_clf_svm_test = clf_svm.predict(X_test)


# summarize the fit of the model
print(metrics.classification_report(expected_clf_svm_test, predicted_clf_svm_test))
print(metrics.confusion_matrix(expected_clf_svm_test, predicted_clf_svm_test))



              precision    recall  f1-score   support

           0       0.94      0.98      0.96       980
           1       0.95      0.99      0.97      1135
           2       0.92      0.90      0.91      1032
           3       0.90      0.91      0.91      1010
           4       0.91      0.93      0.92       982
           5       0.89      0.88      0.88       892
           6       0.92      0.95      0.94       958
           7       0.93      0.91      0.92      1028
           8       0.92      0.87      0.89       974
           9       0.91      0.90      0.90      1009

    accuracy                           0.92     10000
   macro avg       0.92      0.92      0.92     10000
weighted avg       0.92      0.92      0.92     10000

[[ 959    0    1    1    2    6    8    1    2    0]
 [   0 1121    2    2    0    1    3    1    5    0]
 [  13    2  925   14   10    2   23   12   27    4]
 [   4    2   23  918    1   27    2   14   15    4]
 [   1    1    7    0  910   

In [28]:
#neural networks

# fit a simple neuranl network model to the data
model_nn = MLPClassifier(alpha=1, max_iter=1000, 
                       hidden_layer_sizes=(20, 10))

#model_nn = MLPClassifier(solver='sgd', learning_rate_init = 0.001, max_iter=1000, 
                       #hidden_layer_sizes=(5, 2), random_state=1)
    
model_nn.fit(X_train, y_train)
print(model_nn)

# make predictions
expected_nntest = y_test
predicted_nntest = model_nn.predict(X_test)

# summarize the fit of the model
print(metrics.classification_report(expected_nntest, predicted_nntest))
print(metrics.confusion_matrix(expected_nntest, predicted_nntest))


MLPClassifier(alpha=1, hidden_layer_sizes=(20, 10), max_iter=1000)
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.97      0.99      0.98      1135
           2       0.97      0.95      0.96      1032
           3       0.96      0.96      0.96      1010
           4       0.94      0.96      0.95       982
           5       0.94      0.96      0.95       892
           6       0.95      0.95      0.95       958
           7       0.96      0.95      0.95      1028
           8       0.96      0.94      0.95       974
           9       0.96      0.93      0.94      1009

    accuracy                           0.96     10000
   macro avg       0.96      0.96      0.96     10000
weighted avg       0.96      0.96      0.96     10000

[[ 966    0    0    0    0    4    5    1    4    0]
 [   0 1122    2    3    0    1    2    2    3    0]
 [   9    3  978   10   11    0    6   10    5    0]
 [   0    1    

# Performance of the classifier

### Based on the testing accuracy rates of all models >90%, all classifiers are performing extremely well. Among all, SVM and Neural Network seem to be performing the best. The reason for it could be that the MNIST dataset is less linearly separable. SVM and Neural Network are also known to be good fit for multiclass predictions which was the case for this dataset as we were predicting 10 digits.
### One should note that with further tuning, e.g. more hidden layers, the neural network approach has even more room to improve, which likely goes some ways to explaining why deep learning approaches have shown so much success for image classification